# Page settings

baseurl = "http://julien.cloud/"
languageCode = "en-us"
title = "Julien De Freitas Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Julien De Freitas"
        tagline = "☁ Devops Engineer, Technical Lead & Architect | Contractor ☁"
        #avatar = "profile.png"
        avatar = "julienProfile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "cv"
        icon = "fa-file"
        url = "https://goo.gl/eDI0Kh"
        title = "Download Resume"

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: julien@techful.co.uk"
        title = "julien@techful.co.uk"

        #[[params.contact.list]]
        #class = "phone"
        #icon = "fa-phone"
        #url = "tel:+4407516188768"
        #title = "+4407516188768"

        #[[params.contact.list]]
        #class = "website"
        #icon = "fa-globe"
        #url = "//julien.cloud"
        #title = "julien.cloud"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "https://goo.gl/1JXChQ"
        title = "juliendefreitas"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/CliMz"
        title = "github.com/CliMz"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/juliendefreitas"
        title = "@JulienDeFreitas"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Master in Computer Science"
        college = "ITIN"
        dates = "2007 - 2010"

        [[params.education.list]]
        degree = "DUT Network and telecommunication"
        college = "Grenoble University"
        dates = "2004 - 2007"

    # Languages section
    [params.languages]
        enable = true
        title = "Languages"

        [[params.languages.list]]
        language = "French"
        level = "Native"

        [[params.languages.list]]
        language = "English"
        level = "Professional fluent"



    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Running"

        [[params.interests.list]]
        interest = "Crossfit"

        [[params.interests.list]]
        interest = "Cooking"

        [[params.interests.list]]
        interest = "Travel"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "**Technology passionate** I have studied a wide variety of subjects such as electronic, network, telecommunication, project management, coding, entrepreneurship and business. <br> Starting to work as an IT Technician about 10 years ago, I am now a recognised Technology Consultant working on strategic projects for large enterprises. <br>The last 5 years I have endorsed several roles such as cloud architect, cloud consultant, team leader, recruiter, CTO and entrepreneur. <br> These experiences offer me the chance to be able to work on lots of different technical subject, customer context and responsibilities. <br>I enjoy navigating between strong technical knowledge, high-level architecture, vision crafting or team leadership. <br>My experience today allows me to combine soft and technical skills to directly engage with c-level stakeholder to help you building the vital bridge between business and technical implementation and lead technical development to deliver projects.<br><br><br>**As a independant contractor** I provide consulting service to deliver and maintain cloud infrastructure.<br> I can help your organisation to : <br> - Re-design application (micro services)<br> - Lead delivery teams <br> - Plan cloud transformation program / cloud migration <br> - Help business transition on technology, process and knowledges management <br> - Define cloud strategy and new cloud operating model <br> - Evangelise on Devops, Agility and cloud concepts <br> - Design Technical Architecture design (high / low level)<br> - Design Systems Integration design (high / low level)<br> - Optimise OPEX costs<br><br><br>**Open to new opportunities for :** <br> - Challenging projects <br> - Located East or Central London <br> - Contract only <br> - Small team or organisation <br> - No Public Sector"

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Senior Infrastructure Developer"
        dates = "November 2016 - Present"
        company = "Sainsbury's, London | Contract"
        details = "As a member of the Infra Dev team I am working on several project to help delivering devops project. I also evaluated   several way to deploy and maintain Kubernetes cluster and develop and create an automated solution to analyse and propose cost optimisaton accross multiple AWS accounts."


        [[params.jobs.list]]
        position = "Cloud Consultant"
        dates = "July 2015 - Oct 2016"
        company = "Cloudreach, London | Permanent"
        details = "As a Cloud Consultant I endorsed several roles within Cloudreach :<br> - **Cloud architect @ British Petroleum**<br>Design cloud architecture and lead the development of a worldwide enterprise cloud solution. Satisfy security and compliance requirement. Integrate with existing process, tools, infrastructure and network. Drive DevOps patterns with the deployment of automation, workflow engine and log capture tools. Clarify technical concept and cloud paradigm.<br> - **Cloud Consultant @ FCA**<br>I was in charge of creating the roadmap for the cloud transformation phase 2 (Highly available services, Security, Review Best Practices, Identify tech debt etc.) <br> - **Role Owner @ Internal**<br> As the role owner for Cloud Consultant within Cloudreach I created the job description to recruit new consultant, conduct more then 30 interviews, defined evaluation criteria and carrer path for the team."


        [[params.jobs.list]]
        position = "Co-Founder and CTO"
        dates = "Oct 2013 - June 2015"
        company = "Flexinfra, Paris"
        details = "Founder or Flexinfra with 2 friends I was in charge of the technical lead on our private cloud offer and public cloud services. My mission was to : <br> - Design and implementation of cloud infrastructures<br> - Create private and public cloud offers<br> - Modules and interfaces developments<br> - Digital marketing, sales prospection and business networking <br><br> During this period we also achieve outstanding project such as : <br> - **Building partnership** with Alcatel Lucent Enterprise and provide R&D expertise to create a Private Cloud solution offering<br>- **Trainer** for a accelerated training  program to up skill professional to become IT support profesionnals.<br>"

        [[params.jobs.list]]
        position = "Senior ICT Consultant"
        dates = "Jan 2011 - Sept 2013"
        company = "LanExpert, Geneva"
        details = "As a member of the consulting team I was in charge of helping our clients with their IT projects. This involved a lot of different technologies such as : Citrix, Hyper V, Active Directory, DNS, DHCP, BackupExec, Forefront, Remote Desktop Service, Profile Management, SAN, Vmware, LANdesk, Network.<br> "

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "External projects"
        intro = ""

        [[params.projects.list]]
        title = "Senate"
        url = "https://github.com/CliMz/senate"
        tagline = "Open Source project to analyse and propose cloud optimiation on cost, security and architecture best practice."
    
    # Certification section
    [params.certification]
        enable = true
        icon = "fa-certificate"
        title = "certification "
        intro = ""

        [[params.certification.list]]
        title = "AWS"
        tagline = "Certified Solutions Architect - Associate"

        [[params.certification.list]]
        title = "Openstack"
        tagline = "Certified administrator for Openstack - MCA100"

        [[params.certification.list]]
        title = "Microsoft"
        tagline = "MCSA Windows Server 2012R2, MCITP Enterprise Administrator on Windows Server 2008"

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Cloud: AWS, OpenStack, GCP"
        level = "90%"

        [[params.skills.list]]
        skill = "Container : Docker, Kubernetes"
        level = "75%"

        [[params.skills.list]]
        skill = "Automation/CM : Terraform, Ansible, Puppet "
        level = "80%"

        [[params.skills.list]]
        skill = "Scripting : Bash, Python, Golang"
        level = "80%"
                
        [[params.skills.list]]
        skill = "CI/CD : Jenkins, Go.cd, GIT"
        level = "70%"

        [[params.skills.list]]
        skill = "Linux : All Linux Distributions"
        level = "90%"

        [[params.skills.list]]
        skill = "Microsoft : All Windows version"
        level = "95%"

        [[params.skills.list]]
        skill = "Project delivery : Scrum, Jira, Trello, Kanban, Agile Development,"
        level = "75%"


    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
